version: '3.8'

services:
  salary_watcher:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env_docker
    command: >
      /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env_docker
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"